# Challenge 1: Complete Application Setup
# This is a template - students need to complete missing parts

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    tier: frontend
    environment: learning
spec:
  replicas: 2
  selector:
    matchLabels:
      # TODO: Add appropriate selector labels
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        # TODO: Add labels that match the selector
        app: webapp
        tier: frontend
        version: v1.0
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        # TODO: Add environment variables from ConfigMap
        env:
        - name: CUSTOM_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: welcome_message
        
        # TODO: Add resource limits and requests
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        # TODO: Add health checks
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
